# Generated by Django 4.2.16 on 2024-11-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_models', '0002_student_father_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentModel',
        ),
    ]
