# Generated by Django 4.2.16 on 2024-11-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_models', '0003_rename_student_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='father_name',
            field=models.CharField(max_length=20),
        ),
    ]
